Feature: captcha for Reset Password & Resend Confirmation
openware/baseapp pull request #140
Opened 2020-04-17 10:25 UTC by josadcha

2020-04-17 14:24 UTC, akhlopiachyi commented on src/screens/EmailVerification/index.tsx
> +)(EmailVerificationComponent) as any; // tslint:disable-line
replace 'as any' with 'as React.ComponentType'

2020-04-17 14:25 UTC, akhlopiachyi commented on src/screens/ForgotPassword/index.tsx
> +)(ForgotPasswordComponent) as any; // tslint:disable-line
the same as above
Also add an empty line in the end of file

2020-04-20 14:53 UTC, oyershov commented on src/components/EmailForm/index.tsx
> +            'cr-email-form-high': captchaType && captchaType !== 'none',
```suggestion
            'cr-email-form--high': captchaType && captchaType !== 'none',
```

2020-04-20 14:54 UTC, oyershov commented on src/components/EmailForm/index.tsx
> +                                disabled={this.disableButton()}
```suggestion
                                disabled={this.isButtonDisabled()}
```

2020-04-20 14:56 UTC, oyershov commented on src/screens/ForgotPassword/index.tsx
> +        if (nextProps.error) {
```suggestion
        if (nextProps.error && !this.props.error) {
```

2020-05-21 13:49 UTC, pkucherenk0 commented
1. After success or failure resetting the password or confirmation code the checkbox of Recaptcha have to be reset. 
2. On resend confirmation email we should not be able to resend second time without passing new Recaptcha
[vokoscreen-2020-05-21_13-49-52.zip](https://github.com/openware/baseapp/files/4662050/vokoscreen-2020-05-21_13-49-52.zip)
3. On resend confirmation email geetest looks too wide 
![Selection_999(245)](https://user-images.githubusercontent.com/38254545/82565421-12674400-9b83-11ea-841c-b525232ca6cd.png)

2020-08-26 13:13 UTC, josadcha commented
Needs 1-2h to finish

2020-09-07 16:17 UTC, josadcha commented
![Screenshot 2020-09-07 at 19 03 10](https://user-images.githubusercontent.com/39953699/92405618-a9f69f80-f13e-11ea-9968-6731bc226921.png)
fixed styles + add captcha reset in case of error or success

2020-09-15 13:21 UTC, oyershov requested changes
Please, rework this PR.
1. Define separated component <Captha /> with all logic related to the captcha verification
2. Remove all logic related captcha from other components ```EmailVerification```, ```ForgotPassword```, ```SignUpScreen```

2020-09-15 13:21 UTC, oyershov commented on src/components/EmailForm/index.tsx
> +        'cr-email-form--high': captchaType && captchaType !== 'none',
```suggestion
        'cr-email-form--extended': captchaType && captchaType !== 'none',
```

2020-09-15 13:21 UTC, oyershov commented on src/screens/EmailVerification/index.tsx
> +                    <div className="pg-emailverification-recaptcha">
```suggestion
                    <div className="pg-emailverification--recaptcha">
```

2020-09-15 13:21 UTC, oyershov commented on src/screens/EmailVerification/index.tsx
> +                    <div className="pg-emailverification-geetest">
```suggestion
                    <div className="pg-emailverification--geetest">
```

2020-09-17 11:47 UTC, berezh approved these changes

2020-09-17 11:51 UTC, oyershov requested changes

2020-09-17 11:51 UTC, oyershov commented on src/screens/EmailVerification/index.tsx
>  }
move this state to the ```Captcha``` component

2020-09-17 11:51 UTC, oyershov commented on src/screens/EmailVerification/index.tsx
> +    };
move this code to the ```captcha``` component too

2020-09-17 11:51 UTC, oyershov commented on src/screens/ForgotPassword/index.tsx
> +    shouldGeetestReset: boolean;
Same as above.

2020-09-17 11:51 UTC, oyershov commented on src/screens/ForgotPassword/index.tsx
>  }
This is an example of duplicating code

2020-09-22 15:51 UTC, pkucherenk0 commented
1. On the Forgot password page only the first password reset attempt will renew the captcha/geetest, all following attempts will force the user to wait for a minute until the captcha/geetest, will expire by time.

2020-10-02 11:35 UTC, akhlopiachyi approved these changes

2020-10-02 11:35 UTC, merged