Fix: change beneficiary focused field to first
openware/baseapp pull request #311
Opened 2020-09-10 10:07 UTC by oyershov

2020-09-10 16:10 UTC, josadcha requested changes

2020-09-10 16:10 UTC, josadcha commented on src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +                    autoFocus={['coinAddress', 'fiatName'].includes(field) ? true : false}
```suggestion
                    autoFocus={['coinAddress', 'fiatName'].includes(field)}
```

2020-09-14 14:11 UTC, akhlopiachyi approved these changes

2020-09-14 14:17 UTC, josadcha approved these changes

2020-09-14 15:48 UTC, merged