Fix: remove unnecessary check for redirection on email verification s…
openware/baseapp pull request #329
Opened 2020-09-25 11:04 UTC by pkhlopiachyi

…creen

2020-09-25 11:17 UTC, oyershov requested changes

2020-09-25 11:17 UTC, oyershov commented on src/screens/SignInScreen/index.tsx
> +        if (this.props.requireEmailVerification || nextProps.requireEmailVerification) {
```suggestion
        if (!this.props.requireEmailVerification && nextProps.requireEmailVerification) {
```

2020-10-16 13:10 UTC, oyershov approved these changes

2020-10-16 14:07 UTC, akhlopiachyi approved these changes

2020-10-16 14:07 UTC, merged