Feature: Withdraw Confirmation mobile modal
openware/baseapp pull request #330
Opened 2020-09-25 11:40 UTC by josadcha

https://jira.openware.work/browse/CORE-369
![Screenshot 2020-09-25 at 14 34 27](https://user-images.githubusercontent.com/39953699/94262936-f6165200-ff3c-11ea-8dbd-8abf74ecd52a.png)

2020-09-28 11:00 UTC, akhlopiachyi commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +            <div>
i guess you can remove this div

2020-10-02 11:37 UTC, akhlopiachyi approved these changes

2020-10-02 20:25 UTC, VladyslavP requested changes

2020-10-02 20:25 UTC, VladyslavP commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +    const translate = (e: string) => {
why do we need this function?
let's use `formatMessage`

`const { formatMessage } = useIntl();`

and use it everywhere instead

2020-10-02 20:25 UTC, VladyslavP commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +    const renderHeader = () => {
```
const renderHeader = React.useCallback(() =>
 <div className="pg-exchange-modal-submit-header">
        {formatMessage({ id: 'page.mobile.wallet.withdraw.modal.confirmation' })}
 </div>
}, [formatMessage]);
```


We agreed to use useCallback for every function in functional components

2020-10-02 20:25 UTC, VladyslavP commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +        const formattedCurrency = currency.toUpperCase();
we use this variable just once, no need for creating it, use **currency.toUpperCase()** in the code

2020-10-02 20:25 UTC, VladyslavP commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +    const renderBody = () => {
wrap it with useCallback

2020-10-02 20:25 UTC, VladyslavP commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +    const renderFooter = () => {
useCallback

2020-10-21 17:45 UTC, berezh commented on src/mobile/components/ModalWithdrawConfirmation/index.tsx
> +            {renderFooter()}
Fine, but usually, functions are used when there is some logic, for example show or not show. In this case there is no any logic, so you can put that tags inside <Modal/> wihout wrapping them in methods. The code will be more clear, IHMO.

2020-10-22 15:32 UTC, berezh approved these changes

2020-10-22 16:44 UTC, VladyslavP approved these changes

2020-10-22 16:44 UTC, merged