Feature: search dropdown for KYC steps
openware/baseapp pull request #416
Opened 2021-01-19 12:33 UTC by josadcha

2021-01-19 15:42 UTC, akhlopiachyi approved these changes

2021-01-20 09:08 UTC, oyershov requested changes

2021-01-20 09:08 UTC, oyershov commented on src/components/SearchDropdown/index.tsx
> +    const customStyles = {
we are taking a different approach to styling the components in this repo. Please, use `pcss` files for styles instead of styles in tsx.

2021-01-20 09:45 UTC, oyershov approved these changes

2021-01-20 09:47 UTC, merged