Fix: phone verification sendcode logic should cover resend too
openware/baseapp pull request #420
Opened 2021-01-21 10:20 UTC by seanyellowd

https://jira.openware.work/browse/EMI-329

How to test phone verification:
mocks/api/v2/barong/resource/labels/GET.mock
```
  {
      "key":"phone",
      "value":"",
      ...
   }
```

2021-01-21 12:50 UTC, josadcha requested changes

2021-01-21 12:50 UTC, josadcha commented on src/modules/user/kyc/phone/sagas/sendCodeSaga.ts
> +            try {
instead of this code you can call action resendCode

2021-01-21 12:50 UTC, josadcha commented on src/modules/user/kyc/phone/sagas/sendCodeSaga.ts
>              yield put(alertPush({ message: error.message, type: 'success' }));
```suggestion
            yield put(resendCode(action.payload))
```

2021-01-21 12:50 UTC, josadcha commented on src/modules/user/kyc/phone/sagas/sendCodeSaga.ts
>              yield put(alertPush({ message: error.message, type: 'success' }));
pushing alert 'resource.phone.number_exist' is useless, we have sendError action later in code that will do this job

2021-01-22 07:13 UTC, josadcha approved these changes

2021-01-22 09:52 UTC, akushniruk approved these changes

2021-01-22 10:02 UTC, merged