Feature: Add nickname field to the UserData
openware/baseapp pull request #421
Opened 2021-01-21 14:30 UTC by Kohelbekker

2021-01-21 15:57 UTC, josadcha requested changes

2021-01-21 15:57 UTC, josadcha commented on src/api/config.ts
> +    nicknames: false,
better to name it nicknamesEnabled because it's boolean

2021-01-21 15:57 UTC, josadcha commented on src/containers/ProfileAuthDetails/index.tsx
> +                                <h2>Nickname: {user.nickname}</h2>
out Nickname to translations

2021-01-21 15:57 UTC, josadcha commented on src/modules/user/auth/actions.ts
> +        nickname: string;
nickname should be string | undefined

2021-01-21 15:57 UTC, josadcha commented on src/screens/SignUpScreen/index.tsx
>                          captcha_response,
add check here if nickname is enabled

2021-01-22 08:14 UTC, josadcha requested changes

2021-01-22 08:14 UTC, josadcha commented on src/screens/SignUpScreen/index.tsx
>              refId,
This function looks enormous now, could you please rewrite it
For example
const payload = {
   email,
   password,
   refid: refId,
   data: JSON.stringify({
     language: i18n,
  });

Switch captcha_type
...
payload = { ...payload, captcha response}

if (nicknameEnabled) {
    payload = { ...payload, nickname }
}

2021-01-22 09:46 UTC, josadcha approved these changes

2021-01-22 09:51 UTC, akushniruk approved these changes

2021-01-22 10:00 UTC, merged