Fix: nickname validation fixes
openware/baseapp pull request #424
Opened 2021-01-25 09:46 UTC by Kohelbekker

2021-01-25 13:39 UTC, josadcha requested changes

2021-01-25 13:39 UTC, josadcha commented on src/components/SignUp/index.tsx
> +        (isNicknamesEnabled() && !nickname.match(NICKNAME_REGEX))) {
```suggestion
        if (!hasConfirmed || isLoading || !email.match(EMAIL_REGEX) || !password || !confirmPassword ||
           (isNicknamesEnabled() && !nickname.match(NICKNAME_REGEX))) {
```
fix indentation here

2021-01-25 13:39 UTC, josadcha commented on src/components/SignUp/index.tsx
> +                                'cr-sign-up-form__group--errored': nickname.length !== 0 &&
```suggestion
                                'cr-sign-up-form__group--errored': nickname.length &&
```
this is enough to check for length

2021-01-25 14:09 UTC, josadcha approved these changes

2021-01-26 10:51 UTC, akhlopiachyi approved these changes

2021-01-26 11:10 UTC, merged