Feature: Rework Beneficiaries component
openware/baseapp pull request #447
Opened 2021-02-01 15:10 UTC by akhlopiachyi

2021-02-04 08:24 UTC, oyershov requested changes

2021-02-04 08:24 UTC, oyershov commented on src/hooks/useToggle.ts
> +export const useToggle = (initialState) => {
Please remove this hook, it's useless. Use "useState" instead.

2021-02-09 09:49 UTC, oyershov requested changes

2021-02-09 09:49 UTC, oyershov commented on src/components/Beneficiaries/index.tsx
> +    const prevBenefiariesActivateSuccess = usePrevious(beneficiariesActivateSuccess);
There is no need to have `usePrevious` hook. `useEffect` compares old and new properties.

2021-02-09 09:49 UTC, oyershov commented on src/components/Beneficiaries/index.tsx
> +    }, [beneficiariesAddSuccess, currency, prevBeneficiariesAddSuccess, prevBenefiariesActivateSuccess, beneficiariesActivateSuccess]);
1. Separate this hook to multiple `useEffect()`
2. Each hook should do one action. Example:
**This code**
```
React.useEffect(() => {
        if ((props.currency && prevCurrency !== props.currency)
            || (beneficiaries.length && beneficiaries !== prevBeneficiaries)) {
            handleSetCurrentAddressOnUpdate(beneficiaries);
        }
        ...
```
**Should be like this**
```
 React.useEffect(() => {
        if (beneficiaries) {
            handleSetCurrentAddressOnUpdate(beneficiaries);
        }
 }, [beneficiaries]);
```

2021-02-24 08:58 UTC, oyershov approved these changes
LGTM

2021-02-24 15:30 UTC, josadcha requested changes

2021-02-24 15:30 UTC, josadcha commented on src/translations/en.ts
> +    'account.beneficiary.duplicate_address': 'Beneficiary address already existed',
'Beneficiary address already **exists**' please

2021-02-24 15:30 UTC, josadcha commented on src/custom/translations/ru.ts
> +    'account.beneficiary.duplicate_address': 'Beneficiary address already existed',
'Beneficiary address already exists' please

2021-02-24 17:39 UTC, pkucherenk0 commented
Tested locally with master Opendax.
1. After the beneficiary created user will fail to resend the pin or activate it, all API requests will be directed to the `0` id beneficiary
![Selection_999(2057)](https://user-images.githubusercontent.com/38254545/109041761-0db65a00-76d8-11eb-960d-57127dcf0796.png)
![Selection_999(2058)](https://user-images.githubusercontent.com/38254545/109041769-0f801d80-76d8-11eb-91e1-025ef762c49a.png)
2. If a user already has a beneficiary, when he visits the withdraw page beneficiary dropdown opens by it self
2.1 If a user will visit the withdraw of the first currecy with a beneficiary and right after that second currency withdrawal, the beneficiary list will contain a mix of beneficiaries from both currencies 
![Selection_999(2059)](https://user-images.githubusercontent.com/38254545/109041719-03945b80-76d8-11eb-8ed1-d8808be02a12.png)
3. Beneficiary tooltip is behind beneficiary dropdown
![Cryptobase: Wallets - Google Chrome_999(001)](https://user-images.githubusercontent.com/38254545/109041695-fe371100-76d7-11eb-8373-5aa81316ccd1.png)

2021-03-30 07:53 UTC, akushniruk approved these changes

2021-03-30 07:53 UTC, akushniruk commented on web/src/containers/Wallets/History.tsx
> +    public componentWillReceiveProps(nextProps: Props) {
Let's change it to componentDidUpdate

2021-03-30 11:02 UTC, merged