Feature: Implement Wizard pages
openware/baseapp pull request #466
Opened 2021-02-16 00:16 UTC by akhlopiachyi

2021-02-19 10:03 UTC, oyershov commented on src/modules/admin/markets/actions.ts
> +});
Why actions mixed? Please group correctly.

2021-02-19 10:05 UTC, oyershov commented on src/api/types.ts
> +        wizard_step?: number;
fixed

2021-02-19 10:05 UTC, oyershov commented
please, fix tests

2021-02-22 12:57 UTC, oyershov approved these changes

2021-02-22 13:13 UTC, josadcha requested changes

2021-02-22 13:13 UTC, josadcha commented on src/assets/images/setup/ArrowAllRightIcon.tsx
> +export const ArrowAllRightIcon: React.FC<ArrowAllRightIconProps> = (props: ArrowAllRightIconProps) => (
you've defined className prop but haven't use it

2021-02-22 13:13 UTC, josadcha commented on src/assets/images/setup/ArrowLeftIcon.tsx
> +export const ArrowLeftIcon: React.FC<ArrowLeftIconProps> = (props: ArrowLeftIconProps) => (
you've defined className prop but haven't use it

2021-02-22 13:13 UTC, josadcha commented on src/assets/images/setup/ArrowRightIcon.tsx
> +    className?: string;
same

2021-02-22 13:13 UTC, josadcha commented on src/assets/images/setup/CloseSetupIcon.tsx
> +    className?: string;
same

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupCongratsBlock/index.tsx
> +}
better to use stateless component here

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupFormBlock/index.tsx
> +export class SetupFormBlock extends React.Component<SetupFormBlockProps> {
same here, better to use functional component according to our plan about moving Baseapp to func

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupGeneralSettingsForm/index.tsx
> +                        tooltipText="Consequat cupidatat officia duis duis enim voluptate cillum consectetur amet qui commodo proident elit."
add translations please

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupGeneralSettingsForm/index.tsx
> +                        tooltipText="Consequat cupidatat officia duis duis enim voluptate cillum consectetur amet qui commodo proident elit."
same

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupMarketsBlock/index.tsx
> +    public componentWillReceiveProps(nextProps: SetupMarketBlockProps) {
if you don't have enough time to rewrite to functional, at least use componentDidUpdate please

2021-02-22 13:13 UTC, josadcha commented on src/components/SetupComponents/SetupMarketsBlock/index.tsx
> +                                <ArrowLeftIcon /><span>Add</span>
also missing translations in this file

2021-02-22 13:13 UTC, josadcha commented on src/modules/admin/markets/sagas/updateMarketSaga.ts
> +        yield put(alertPush({message: ['Market updated created'], type: 'success'}));
add to translations please

2021-02-22 13:26 UTC, josadcha approved these changes

2021-02-22 13:29 UTC, oyershov commented
Merged with note.
1. Refactor asap using functional approach
**2. Add translations**
3. Use separate color variables for the setup pages

2021-02-22 13:30 UTC, merged