Quick exchange history tab
openware/baseapp pull request #501
Opened 2021-03-09 03:39 UTC by TeeSrisantitham

2021-03-10 08:01 UTC, akushniruk requested changes

2021-03-10 08:01 UTC, akushniruk commented on web/mocks/api/v2/peatio/market/orders/GET--page=1&limit=25&market_type=qe.mock
> +    "funds_received":"1"
is it the correct response?

2021-03-10 08:01 UTC, akushniruk commented on web/src/containers/HistoryElement/index.tsx
> +        if (type === 'quick') fetchParams['market_type'] = 'qe';
rewrite it to
```
if (type === 'quick_exchange') {
    fetchParams['market_type'] = 'qe';
}```

2021-03-10 09:30 UTC, TeeSrisantitham commented on web/src/containers/HistoryElement/index.tsx
> +                const marketToDisplay = marketsData.find(m => m.id === market) ||
In this line, I filter market data by market id from an item to get display data ex. base quote. I don't understand why we have to filter markets with 'qe' ?

2021-03-10 10:07 UTC, akushniruk commented on web/src/containers/HistoryElement/index.tsx
> +                const marketToDisplay = marketsData.find(m => m.id === market) ||
idk but maybe we can have 2 markets with the same id but with different type

2021-03-11 06:59 UTC, TeeSrisantitham commented on web/mocks/api/v2/peatio/market/orders/GET--page=1&limit=25&market_type=qe.mock
> +    "funds_received":"1"
@dpatsora Please check?

2021-03-11 18:57 UTC, akushniruk commented on web/src/containers/HistoryElement/index.tsx
> +                const marketToDisplay = marketsData.find(m => m.id === market) ||
all is ok we fetch only with type: 'qe'

2021-03-17 09:49 UTC, oyershov requested changes

2021-03-17 09:49 UTC, oyershov commented on web/src/containers/HistoryElement/index.tsx
> +                const marketToDisplay = marketsData.find(m => m.id === market) || defaultMarket;
```suggestion
                const marketToDisplay = marketsData?.find(m => m.id === market) || defaultMarket;
```

2021-03-17 09:49 UTC, oyershov commented on web/src/containers/HistoryElement/index.tsx
> +                        currencyReceive: marketToDisplay.base_unit.toUpperCase(),
```suggestion
                        amountGive: (+price || 0) * (+origin_volume || 0),
                        amountReceive: (+origin_volume || 0),
                        givePrecision: marketToDisplay?.price_precision || DEFAULT_PRECISION,
                        receivePrecision: marketToDisplay?.amount_precision || DEFAULT_PRECISION,
                        currencyGive: marketToDisplay?.quote_unit?.toUpperCase(),
                        currencyReceive: marketToDisplay?.base_unit?.toUpperCase(),
```

2021-03-17 09:49 UTC, oyershov commented on web/src/containers/HistoryElement/index.tsx
> +                    data = {
same as above

2021-03-17 09:49 UTC, oyershov commented on web/src/containers/HistoryElement/index.tsx
> +                    <Decimal key={id} fixed={data.givePrecision} thousSep=",">{data.amountGive}</Decimal>,
```suggestion
                    <Decimal key={id} fixed={data?.givePrecision || DEFAULT_PRECISION} thousSep=",">{data.amountGive}</Decimal>,
```

2021-03-17 09:49 UTC, oyershov commented on web/src/containers/HistoryElement/index.tsx
> +                    <Decimal key={id} fixed={data.receivePrecision} thousSep=",">{data.amountReceive}</Decimal>,
same as above

2021-09-27 09:19 UTC, akushniruk commented
not need anymore + it's difficult to rebase on master

2021-09-27 09:19 UTC, closed without merging