Feature: add quick exchange
openware/baseapp pull request #505
Opened 2021-03-09 14:10 UTC by akushniruk

2021-03-15 10:47 UTC, akushniruk commented on web/mocks/api/v2/finex/public/market/qe/prices/GET--market=btceth&side=sell.mock
> +HTTP/2 200
web/mocks/api/v2/finex/public/market/qe/prices/GET--market=btceth&side=sell.mock ->  web/mocks/api/v2/finex/public/qe/prices/GET--market=btceth&side=sell.mock

2021-03-15 10:47 UTC, akushniruk commented on web/mocks/api/v2/finex/public/market/qe/prices/GET--market=btceth&side=buy.mock
> +HTTP/2 200
web/mocks/api/v2/finex/public/market/qe/prices/GET--market=btceth&side=buy.mock ->web/mocks/api/v2/finex/public/qe/prices/GET--market=btceth&side=buy.mock

2021-03-15 10:47 UTC, akushniruk commented on web/mocks/api/v2/sonic/public/config/GET.mock
> +    "withCredentials": "false",
add msPricesUpdates

2021-03-15 10:47 UTC, akushniruk commented on web/src/components/Timer/index.ts
> +    return null;
let's add props for showing the timer for the user.
```props.showTimer ? renderTimer() : null```

``` const renderTimer = () => return (+minutes === 0 && +seconds === 0 ?
           <div className={props.className}>00:00</div>
          :
          <div className={props.className}>{+minutes < 10 ?`0${minutes}` : minutes}:{+seconds < 10 ?  `0${seconds}` : seconds}</div>
    )
```

and maybe need move it to react-components?

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +    const marketQuoteUnits = markets.map(item => item.quote_unit);
let's combine it into 1 map; 
```const marketUnits = markets.map(item => [item.base_unit, item.quote_unit]).flat();```

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +const onlyUnique = (value, index, self) => self.indexOf(value) === index;
we do not need it

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +    const marketCurrencies =  marketBaseUnits.concat(...marketQuoteUnits).filter(this.onlyUnique);
just use type Set
``` const marketCurrencies = new Set(marketUnits)```

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +const getMarket = (marketID: string, markets: Market[]) => {
let's rewrite it to 1 line

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +const getWallet = (currency: string, wallets: Wallet[]) => {
let's rewrite it to 1 line

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/helpers.ts
> +    quoteCurrency: string,
we need to find a better name for it

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                        You exchange
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                    Icons
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                        You receive
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                    Estimated price: <span>~{marketPrice.price} {base.currency.toUpperCase()}</span>
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                    Slippage is higher than 1%. Enter a lower amount to get a better price
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                        Exchange
add translate()

2021-03-15 10:47 UTC, akushniruk commented on web/src/modules/public/markets/sagas/marketPriceSaga.ts
> +        const price = yield call(API.get(marketPriceRequestOptions), `/public/market/qe/prices?${payload}`);
public/qe/prices?market=btceth&side=sell >>> "{\"price\":\"200\",\"created_at\":1615797266,\"updated_at\":1615797266}\n"

2021-03-17 08:55 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                            <span>Min exchange amount is {currentSelectedMarket.min_amount} {walletBase.currency.toUpperCase()}</span>
add translate()

2021-03-17 08:55 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                            Balance: <span>{walletBase.balance} {walletBase.currency.toUpperCase()}</span>
add translate()

2021-03-17 08:55 UTC, akushniruk commented on web/src/containers/QuickExchange/index.tsx
> +                    <span>Slippage is higher than 1%. Enter a lower amount to get a better price</span>
add translate()

2021-03-17 08:55 UTC, akushniruk commented on web/src/modules/user/quickExchange/sagas/createQuickExchangeOrderSaga.ts
> +        yield put(alertPush({message: ['success.quick.exchange.order.created'], type: 'success'}));
add translation for it

2021-03-17 09:42 UTC, oyershov requested changes

2021-03-17 09:42 UTC, oyershov commented on web/src/components/Dropdown/index.tsx
> +    }, [props.selectedValue]);
1. Combine these 2 useEffects into one as it affects to the same variable.
2. We have type checks in the `convertToString`. This should be ok:
```suggestion
    useEffect(() => {
        if (clear !== false) {
            setSelected(convertToString(placeholder || defaultPlaceholder)));
        }
    }, [placeholder, defaultPlaceholder, clear, props.selectedValue]);
```

2021-03-17 09:42 UTC, oyershov commented on web/src/components/QuickExchangeForm/index.tsx
> +    }, [props.value]);
Please, remove. This function doesn't affect any value in this component.

2021-03-17 09:42 UTC, oyershov commented on web/src/components/Timer/index.tsx
> +    initialMinutes: number;
please remove Minutes and use only seconds

2021-03-17 09:42 UTC, oyershov commented on web/src/components/Timer/index.tsx
> +                <div className={props.className}>{+minutes < 10 ?`0${minutes}` : minutes}:{+seconds < 10 ?  `0${seconds}` : seconds}</div>
calculate minutes from seconds

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/QuickExchange.pcss
> +              border-bottom: 1px solid #e3e9f1 !important;
don't hardcode colors, use variables. Not only here, check all changes you did

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/helpers.ts
> +const getAvailableValue = (wallet: Wallet | undefined) => wallet ? wallet.balance : 0;
why do you need this helper? Please, just put this check where you use it

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/helpers.ts
> +const cleanPositiveFloatInput = (text: string) => {
Duplicating functional. Use `web/src/helpers/cleanPositiveFloatInput.ts` (+ it's covered by tests)

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +    const [time, setTime] = useState<QuickExchangeTimer>(DEFAULT_VALUE_TIMER);
This is ok, but better to use `useReducer` instead of `useState` for such case when we have more than 2 state variables.

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +        getWallets(wallets, marketsQuoteUnit), [wallets, marketsQuoteUnit]);
This definitely should be changed. `useMemo` will call `getWallets` or `getCurrencyFiltred` but will not re-render component. Still we have here performance issue.
You can find details here: https://reactjs.org/docs/hooks-reference.html#usememo
Replace it with `useCallback `

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +        const value = walletsBaseList[index];
```suggestion
        const value = walletsBaseList?.[index];
```

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +        const marketExists = markets.some(item => item.id === (value + quote.currency).toLowerCase());
```suggestion
        const marketExists = markets?.some(item => item.id === (value + quote?.currency)?.toLowerCase());
```

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +            market.id = (value + quote.currency).toLowerCase();
```suggestion
            market.id = (value + quote?.currency)?.toLowerCase();
```

2021-03-17 09:42 UTC, oyershov commented on web/src/containers/QuickExchange/index.tsx
> +    const handleChangeDropdownQuote = React.useCallback((index: number) => {
Remove duplicating functional. There is no need to have 2 almost similar functions `handleChangeDropdownBase` and `handleChangeDropdownQuote`. Pass `side` as parameter.

2021-03-17 09:42 UTC, oyershov commented on web/src/modules/public/markets/sagas/marketPriceSaga.ts
> +        const price = yield call(API.get(marketPriceRequestOptions), `/public/qe/prices?${payload}`);
Wrong query build. If there will be no payload - request URL will looks like `/public/qe/prices?`. Please, handle this.

2021-03-17 09:42 UTC, oyershov commented on web/src/modules/public/markets/sagas/marketsFetchSaga.ts
> +        const request = payload && payload.type ? `/public/markets?type=${payload.type}` : '/public/markets';
use `buildQueryString`

2021-03-17 09:42 UTC, oyershov commented on web/src/modules/public/markets/sagas/tickersSaga.ts
> +                result[pair] = tickers[pair].ticker;
What if there will be no nested `ticker` in the structure?
1. Define types or use existing interface.
2. Separate to another function and cover with unit tests.

2021-03-17 09:42 UTC, oyershov commented on web/src/modules/user/quickExchange/reducer.ts
> +                fetching: false,
add next line:
`error: undefined`

2021-03-30 06:46 UTC, closed without merging