Enhancement: Add latest sonic changes
openware/baseapp pull request #508
Opened 2021-03-12 09:14 UTC by vshatravenko

* Add Engine creation + market update changes

2021-03-29 16:29 UTC, akhlopiachyi approved these changes

2021-03-30 06:52 UTC, akushniruk requested changes

2021-03-30 06:52 UTC, akushniruk commented on views/index.html
> +    </head>
better to put it in master.html because we need apply CSS from baseapp to SSR UI components

2021-03-30 06:52 UTC, akushniruk commented on views/index.html
> +        {{end}}
should be in master.html. In the future, we want to apply react-hydrate

2021-03-30 06:52 UTC, akushniruk commented on web/src/components/CombinedOrderBook/index.tsx
>      public componentWillReceiveProps(next: CombinedOrderBookProps) {
let's change it to componentDidUpdate

2021-03-30 06:52 UTC, akushniruk commented on web/src/containers/OrderBook/index.tsx
> +            setTimeout(() => {
For what we need set timeout in this place?

2021-03-30 10:47 UTC, akushniruk approved these changes

2021-03-30 10:49 UTC, merged