Fix: incorrect receive amount in confirm order modal
openware/baseapp pull request #600
Opened 2021-04-29 04:34 UTC by dhanuwat

[Jira Ticket](https://openware-inc.atlassian.net/browse/NAIR-211)

Fix incorrect confirm receive amount in checkbox of order confirmation modal.

2021-04-29 10:34 UTC, josadcha requested changes

2021-04-29 10:34 UTC, josadcha commented on web/src/containers/P2P/OrderWaitPayment/index.tsx
> +                            // label={translate(`page.body.p2p.order.transfer.order.wait.confirm.checkbox.${order?.state}`, order && { amount: `${order.amount} ${order?.offer?.quote?.toUpperCase()}`
could you please remove commented line

2021-04-30 07:35 UTC, dhanuwat commented on web/src/containers/P2P/OrderWaitPayment/index.tsx
> +                            // label={translate(`page.body.p2p.order.transfer.order.wait.confirm.checkbox.${order?.state}`, order && { amount: `${order.amount} ${order?.offer?.quote?.toUpperCase()}`
Fixed, thanks.

2021-04-30 07:45 UTC, josadcha approved these changes

2021-04-30 07:45 UTC, merged