Feature: advanced Open Orders from Finex API
openware/baseapp pull request #664
Opened 2021-05-25 14:52 UTC by josadcha

2021-05-26 08:44 UTC, akushniruk approved these changes

2021-05-26 08:58 UTC, akhlopiachyi commented on web/src/containers/OpenOrders/index.tsx
> +}
maybe better to create helpers.ts inside web/src/containers/OpenOrders folder and move this function there?

2021-05-26 08:59 UTC, akhlopiachyi commented on web/src/containers/OpenOrders/index.tsx
>          if (list.length === 0) {
!list.length

2021-05-26 09:00 UTC, akhlopiachyi commented on web/src/containers/OpenOrders/index.tsx
> +        }),
move `),` to next line

2021-05-26 09:01 UTC, akhlopiachyi commented on web/src/containers/OpenOrders/index.tsx
> +            )}
Please create a method using useMemo that returns html depends on `fetching` value

2021-05-26 09:02 UTC, akhlopiachyi commented on web/src/modules/user/openOrders/actions.ts
>          market: Market,
please replace `market: Market,` with `market: Market;`

2021-05-31 17:30 UTC, akhlopiachyi commented on web/src/containers/OrdersElement/index.tsx
>      };
I guess be better to create a helpers file for OrdersElement and move this function there

2021-05-31 17:30 UTC, akhlopiachyi approved these changes

2021-06-15 10:49 UTC, akushniruk commented on web/src/containers/OpenOrders/index.tsx
> +                <span key={id}><Decimal fixed={amountFixed} thousSep=",">{+remaining_volume}</Decimal> <span className="cr-text__opacity">{curMarket?.quote_unit?.toUpperCase()}</span></span>,
multiply by price

2021-06-24 12:11 UTC, akushniruk requested changes

2021-06-24 12:11 UTC, akushniruk commented on web/src/components/OrderForm/index.tsx
> +            priceToUse = (Number(priceToUse) * 1.1).toString()
pls put 1.1 to the constants file

2021-06-24 12:40 UTC, akushniruk approved these changes

2021-06-24 12:43 UTC, merged