Fix: make /quick-exchange accessible via link
openware/baseapp pull request #709
Opened 2021-06-25 12:51 UTC by Kohelbekker

2021-06-29 09:14 UTC, josadcha requested changes

2021-06-29 09:14 UTC, josadcha commented on web/src/containers/QuickExchange/index.tsx
> +        if (abilities.read && !CanCan.checkAbilityByAction('read', 'QuickExchange', abilities)) {
better to check if abilities has been successfully fetched because [read] might be empty, while [update] might be fulfilled

2021-06-29 09:14 UTC, josadcha commented on web/src/containers/QuickExchange/index.tsx
> +            {!abilities.read ? renderLoader() :
same here

2021-06-29 09:14 UTC, josadcha commented on web/src/routes/Layout/index.tsx
> +                    <PrivateRoute loading={userLoading} isLogged={isLoggedIn} path="/quick-exchange" component={QuickExchange} />
please remove `checkAbility` from <PrivateRoute /> since that logic doesn't work correctly as we have already seen with QA example

2021-07-02 15:06 UTC, josadcha requested changes

2021-07-02 15:06 UTC, josadcha commented on web/src/containers/QuickExchange/index.tsx
> +    console.log(abilitiesSuccess);
remove Please

2021-07-02 15:06 UTC, josadcha commented on web/src/containers/QuickExchange/index.tsx
> +        if (abilitiesSuccess && !CanCan.checkAbilityByAction('read', 'QuickExchange', abilities)) {
add please abilitiesSuccess to dependency array at line https://github.com/openware/baseapp/blob/5aafee6ad463bde57e5b27839783681343933d8d/web/src/containers/QuickExchange/index.tsx#L97

2021-07-02 15:14 UTC, josadcha approved these changes

2021-07-02 15:47 UTC, akhlopiachyi commented on web/src/containers/QuickExchange/index.tsx
> +            (
move this to previous line and fix indentation

2021-07-05 07:39 UTC, akhlopiachyi commented on web/src/containers/QuickExchange/index.tsx
> +    const renderLoader = () => (
Use react.useMemo

2021-07-05 07:48 UTC, akhlopiachyi approved these changes

2021-07-05 08:08 UTC, merged