Feature: add error translation for barong rack-attack error
openware/baseapp pull request #711
Opened 2021-06-28 20:44 UTC by Kohelbekker

2021-06-29 09:05 UTC, josadcha requested changes

2021-06-29 09:05 UTC, josadcha commented on web/src/modules/public/alert/sagas/handleAlertSaga.ts
> +                return;
the action `callAlertData` is called by default, no need to move that to separate case

2021-07-05 07:36 UTC, pkucherenk0 commented on web/src/custom/translations/ru.ts
> +    'identity.session.rack_attack_limit': 'Limit of of signin requests is exceeded, please try again it 60 seconds',
The limit of signing requests exceeded, please try again in 60 seconds

2021-07-05 07:36 UTC, pkucherenk0 commented on web/src/translations/en.ts
> +    'identity.session.rack_attack_limit': 'Limit of of signin requests is exceeded, please try again it 60 seconds',
The limit of signing requests exceeded, please try again in 60 seconds

2021-07-05 09:33 UTC, josadcha approved these changes

2021-07-07 06:54 UTC, akushniruk approved these changes

2021-07-07 06:54 UTC, merged