Fix: add price precision for data in table on landing page
openware/baseapp pull request #713
Opened 2021-06-30 18:16 UTC by dmitrydenisov183

https://openware-inc.atlassian.net/browse/OPD-449

Added price_precision for table on the Landing page
![image](https://user-images.githubusercontent.com/38152090/124002336-0b01a380-d9ef-11eb-81a0-543fa0d64ac5.png)

2021-07-01 06:58 UTC, josadcha requested changes

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +    isFixedPrecision: boolean
please remove this prop, there is no case when we need Market table without fixed precision.

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +const FIXED_PRECISION = 2;
name this as FIXED_VOL_PRECISION, move to src/constants.ts file and import here

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +                            <Decimal fixed={!isFixedPrecision ? market.amount_precision : market.price_precision} thousSep=",">
Market.last is market last price. For displaying price we use market.price_precision.

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +                            <Decimal fixed={!isFixedPrecision ? market.amount_precision : market.price_precision} thousSep=",">
same for market.high, it's the highest price within 24h, so again for price we use price_precision.

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +                            <Decimal fixed={!isFixedPrecision ? market.amount_precision : market.price_precision} thousSep=",">
same here

2021-07-01 06:58 UTC, josadcha commented on web/src/components/TickerTable/index.tsx
> +                            <Decimal fixed={!isFixedPrecision ? market.amount_precision : FIXED_PRECISION} thousSep=",">
market.volume is a value in quote currency. that's why here we also put market.price_precision

2021-07-01 06:58 UTC, josadcha commented on web/src/containers/MarketsTable/index.tsx
> +            isFixedPrecision={props.isFixedPrecision}
no need for this

2021-07-01 06:58 UTC, josadcha commented on web/src/mobile/screens/Landing/index.tsx
> +            <MarketsTable isFixedPrecision />
remove please this change

2021-07-01 06:58 UTC, josadcha commented on web/src/screens/LandingScreen/index.tsx
> +                            <MarketsTable isFixedPrecision />
remove please this change

2021-07-01 12:22 UTC, josadcha approved these changes

2021-07-02 12:15 UTC, akhlopiachyi approved these changes

2021-07-02 12:47 UTC, merged