Feature: Add xlm, eos, luna, xem as memo based currencies
openware/baseapp pull request #790
Opened 2021-09-21 07:41 UTC by xenirio

2021-09-22 10:40 UTC, josadcha requested changes

2021-09-22 10:40 UTC, josadcha commented on web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +    const isMemoTagExists = React.useMemo(() => CURRENCIES_MEMO.includes(currency), [currency]);
move this to helpers, they're going to be reusable

2021-09-22 10:40 UTC, josadcha commented on web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +    const isMemoTagExists = React.useMemo(() => CURRENCIES_MEMO.includes(currency), [currency]);
requiresTag
requiresMemo

2021-09-22 10:40 UTC, josadcha commented on web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +        }
```suggestion
        const address = requiresTag(currency) && coinDestinationTag ? `${rid}?dt=${tagMemo}`
            : requiresMemo(currency) && coinDestinationTag ? `${rid}?memo=${tagMemo}`
            : rid;
```

no need to make such a big function

2021-09-22 10:40 UTC, josadcha commented on web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +                if ((isDestinationTagExists || isMemoTagExists) && value.includes('?')) {
add please these functions to helpers

```
export const getMemoTag = (value?: string) => {
    if (value && (value.includes('?dt=') || value.includes('?memo='))) {
        return value.substr(value.lastIndexOf('=') + 1);
    }

    return '-';
};

export const getAddressWithoutMemoTag = (value?: string) => {
    if (value && (value.includes('?dt=') || value.includes('?memo='))) {
        return value.slice(0, value.lastIndexOf('?'));
    }

    return value;
};

```

2021-09-24 03:14 UTC, calj commented on web/src/helpers/memoBasedAsset.ts
> +export const getMemoTag = (value?: string) => {
dt means "destination tag", please rename

2021-09-24 03:14 UTC, calj commented on web/src/constants/index.ts
> +export const CURRENCIES_MEMO = ['xlm', 'eos', 'luna', 'xem'];
please define a constant CURRENCIES_DT, even if there is only xrp in it

2021-09-27 03:50 UTC, calj approved these changes

2021-09-27 09:04 UTC, akushniruk approved these changes

2021-09-27 09:04 UTC, akushniruk commented on web/src/components/Beneficiaries/BeneficiariesAddModal.tsx
> +    const isMemoTagExists = requiresMemoTag(currency) === true;
change: ```requiresDTTag(currency) === true``` to ```requiresDTTag(currency)```

2021-09-27 09:28 UTC, josadcha approved these changes

2021-09-27 09:29 UTC, merged