Fix: 3.1 input fields and label style (WIP)
openware/baseapp pull request #792
Opened 2021-09-21 10:57 UTC by seanyellowd

https://openware-inc.atlassian.net/browse/OPD-798

2021-09-24 06:52 UTC, akushniruk commented on web/src/containers/ProfilePayment/PaymentMethodModal.tsx
> +                        <label></label>
can we remove it?

2021-09-24 06:52 UTC, akushniruk approved these changes

2021-09-24 06:56 UTC, akushniruk requested changes

2021-09-24 06:56 UTC, akushniruk commented on web/src/containers/ModalWithdrawConfirmation/index.tsx
> +        }
add case: `prevProps.show !== this.props.show`

2021-09-27 06:34 UTC, akushniruk approved these changes

2021-09-27 09:34 UTC, Kohelbekker approved these changes

2021-09-27 09:45 UTC, merged