Fix: display status for withdraw and deposit history
openware/baseapp pull request #793
Opened 2021-09-22 10:13 UTC by dhanuwat

[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-842)
[Jira Ticket](https://openware-inc.atlassian.net/browse/OPD-844)

Fix incorrect display status on wallet deposit and withdraw history table.

2021-09-22 10:19 UTC, josadcha requested changes

2021-09-22 10:19 UTC, josadcha commented on web/src/custom/translations/ru.ts
> +    'page.body.wallets.table.confirming': 'подтверждающий',
could yo please change to 'Подтверждается'

2021-09-23 07:25 UTC, akushniruk approved these changes

2021-09-23 07:33 UTC, akhlopiachyi approved these changes

2021-09-23 08:26 UTC, josadcha approved these changes

2021-09-23 08:27 UTC, merged